### ISSUE TITLE
Parsing \@

### ISSUE THREAD

**Issue by dyp-cpp** [Eelis/cxxdraft-htmlgen#1]
The LaTeX `\@` modifies whether or not a dot `.` is interpreted as the end of a sentence (for spacing), see http://latex-alive.tumblr.com/post/827168808/correct-punctuation-spaces.
(Unfortunately, I don't know the name of `\@`)

The HaTeX parser doesn't deal correctly with it, it produces something like `TeXSeq (TeXCommS "") (TeXRaw "@")`, which in turn produces a visible `@` in the HTML output. See [[intro.structure]p4](http://eel.is/c++draft/intro#intro.structure-4)

Given enough time, I'll submit a fix, so you could consider this a memo.

**Comment by Eelis** [comment]
Thanks for the fix!
