### ISSUE TITLE
Some parts of index not correctly rendered

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#10]
We have some stray quotes:

>    "!, see operator, logical negation
>    "!=, see inequality operator

followed by some missing quotes (this should be `"..."`)
>    ..., see preprocessing directives, source-file inclusion

followed by more stray quotes:
>    "|, see bitwise inclusive OR operator
>    "|"|, see logical OR operator

In the middle we have

>    _, see character, underscore, see operator, ones' complement

The second "see" is for `~`, but it disappeared.

And then there's

>    exception, [exception.syn]
>        arithmetic, [expr]
>        undefined arithmetic, [expr]

This mixed `<exception>` and "exception". In the standard it is 

>    exception
>        arithmetic, [expr]
>        undefined arithmetic, [expr]
>    <exception>, [exception.syn]

It'd also be nice if all the special characters are together, like in the standard, rather than scattered all over the index.

**Comment by Eelis** [comment]
Fixed, thanks!
