### ISSUE TITLE
[cpp.predefined] Sub-links to feature macro version number constants overlayed with `⟵` arrow, making it unreadable

### ISSUE THREAD

**Issue by whisperity** [Eelis/cxxdraft-htmlgen#100]
For example when going from the [index row of `__cpp_modules`](http://eel.is/c++draft/generalindex#:__cpp_modules) to [`[cpp.predefined]#:__cpp_modules`](http://eel.is/c++draft/cpp.predefined#:__cpp_modules), there is an `⟵` arrow which is not clickable and leads nowhere, but is overlaying the first *3* characters of the macro value literal:

![Screenshot_20230215_164527](https://user-images.githubusercontent.com/1969470/219077901-eb7df8b3-835d-475f-947a-713dc17a3d0d.png)

**Comment by Eelis** [comment]
Thanks for the report.
