### ISSUE TITLE
Feature request: Support searching text

### ISSUE THREAD

**Issue by nickpdemarco** [Eelis/cxxdraft-htmlgen#101]
Hello, thank you for maintaining this invaluable resource for C++ research.

My work often requires I find all uses of a particular phrase (say, "undefined" or "invalid") in the standard drafts. It would be immensely useful if http://www.eel.is/c++draft/ had a simple search feature could find and present in aggregate all (sub)sections containing a particular word or phrase.

Sadly, [google's index of the site](https://www.google.com/search?q=site%3Ahttp%3A%2F%2Fwww.eel.is%2Fc%2B%2Bdraft%2F+undefined&biw=1901&bih=1063&ei=tcoIZNeSNe6s5NoP6pmnwAc&ved=0ahUKEwiXwfa48sz9AhVuFlkFHerMCXgQ4dUDCBA&uact=5&oq=site%3Ahttp%3A%2F%2Fwww.eel.is%2Fc%2B%2Bdraft%2F+undefined&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVD1AVjTCGChCWgCcAB4AIABaogB2gSSAQM4LjGYAQCgAQHAAQE&sclient=gws-wiz-serp) appears incomplete.

**Comment by JohelEGP** [comment]
It's not an aggregate of sections, but try using your browser's search feature at https://eel.is/c++draft/full. `full` is documented in the README.

**Comment by Eelis** [comment]
Yeah, this is what `/full` is for.

You can also get better Google results by omitting the `www.` and just using `site:eel.is/c++draft`.
