### ISSUE TITLE
Why is there noto serif font on eel.is/c++draft which is missing in git

### ISSUE THREAD

**Issue by hanickadot** [Eelis/cxxdraft-htmlgen#105]
Hi, I'm sorry, this is not actually an issue; just a question.

Why is at eel.is different font than it should be generated by the latest master commit d7af541

```html
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Noto+Serif">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Noto+Sans">
```

Are you using different version of scripts to generate the webpage?

**Comment by JohelEGP** [comment]
> `eel.is/c++draft` is occasionally a few commits ahead of github, in this case because I'm experimenting with different fonts.

-- <https://github.com/Eelis/cxxdraft-htmlgen/issues/104#issuecomment-1695431714>.

**Comment by hanickadot** [comment]
Oh, thank you! Mystery solved :)
