### ISSUE TITLE
New font family name and white spaces

### ISSUE THREAD

**Issue by stefanos82** [Eelis/cxxdraft-htmlgen#106]
For years I knew font family names that contain white spaces they were enclosed in double quotes as a good practice: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names

In my humble opinion, it gives the wrong impression that consists of 3 separate font names: `font-family: Noto Sans Mono;` whereas `font-family: "Noto Sans Mono";` makes it more obvious it's just a single font-family name.

Any particular reason you are not enclosing new font in double quotes?

**Comment by Eelis** [comment]
Thanks, I didn't know about that convention.
