### ISSUE TITLE
The italic style for `\exposid` is lost when nested within `$$`

### ISSUE THREAD

**Issue by frederick-vs-ja** [Eelis/cxxdraft-htmlgen#109]
Originally reported as cplusplus/draft#6717. The problem still exists in [[range.repeat.iterator]](https://eel.is/c++draft/range.repeat.iterator) generated on 2023-12-30, while [N4971](https://wg21.link/n4971) correctly preserved the italic style.

Source:
https://github.com/cplusplus/draft/blob/8410aac1b84ec161b6990441acde53185f958135/source/ranges.tex#L3685-L3686

https://github.com/cplusplus/draft/blob/8410aac1b84ec161b6990441acde53185f958135/source/ranges.tex#L3721-L3722

https://github.com/cplusplus/draft/blob/8410aac1b84ec161b6990441acde53185f958135/source/ranges.tex#L3741-L3742

**Comment by Eelis** [comment]
Thanks for the report!
