### ISSUE TITLE
Link back to parent page sometimes goes to nonexistent anchor

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#13]
For example, in http://timsong-cpp.github.io/draft/dcl.init.string (generated today), the link to `[dcl.init]` at the top goes to http://timsong-cpp.github.io/draft/dcl.init#dcl.init.string, which doesn't exist. The actual anchor is http://timsong-cpp.github.io/draft/dcl.init#string.

**Comment by Eelis** [comment]
Fixed, thanks!
