### ISSUE TITLE
'itemize' inside 'indented'

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#16]
When using the tool (with the new grammar & charname.tex changes reverted) on N3337 and N4140 sources, I noticed that it chokes on a section of conversions.tex that has something like

    \begin{indented}
    ...
    \begin{itemize}
    ...
    \end{itemize}
    \end{indented}

with an 'unexpected env itemize' error. I worked around this by [removing the 'indented'](https://github.com/timsong-cpp/draft/commit/9304721c82014beabb8296a09e5a0400f778953a) in the LaTeX, but maybe it's easy to change the code to accommodate this?

**Comment by Eelis** [comment]
Sorry, but cxxdraft-htmlgen only targets upstream master. Maintaining compatibility with historical versions of the sources (which differ not only in content but also in how they use environments/macros) is too much work and the code is complex enough as it is.

If you're interested in running cxxdraft-htmlgen on historical versions of the document, you'll have to maintain the branches yourself.

**Comment by timsong-cpp** [comment]
No worries. I was just wondering if it'd be a trivial change, as this environment combination doesn't seem too unreasonable and might pop up again. I'm happy with the workaround I have.
