### ISSUE TITLE
Additional line breaks introduced in [nullablepointer.requirements]/3 by Eelis/draft@03f09e2

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#20]
https://github.com/Eelis/draft/commit/03f09e26aee2e67c20d04f086b05b6ed3a6e6077#diff-70346be2d86a88af3b58e886175e3a84R1661 added two line breaks in the tex source, which caused a (presumably unintended) paragraph break in http://eel.is/c++draft/nullablepointer.requirements#3.

**Comment by Eelis** [comment]
Ah, fixed, thanks.
