### ISSUE TITLE
[fs.definitions] mishandled

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#22]
The top level, 30.10.4 [fs.definitions] [is blank](https://timsong-cpp.github.io/cppwp/fs.definitions); the items are numbered as 30.10.5 etc. rather than 30.10.4.1. This causes what is section 30.10.5 [fs.req] in the working draft to be numbered 30.10.24 instead in the HTML.

**Comment by Eelis** [comment]
Fixed, thanks for the report.
