### ISSUE TITLE
Installation directions are largely incomplete and/or broken

### ISSUE THREAD

**Issue by willkill07** [Eelis/cxxdraft-htmlgen#23]
Disclosure: I'm relatively new to haskell, but I've been able to successfully build/install/use other packages in the past

I installed all of the dependences using `brew` (and `brew cask`) on macOS.

* `brew cask install haskell-platform`
* `brew install nodejs graphviz`
* `npm install mathjax-node`

I first attempted to just run `runhaskell genhtml.hs /path/to/draft` but it failed because it couldn't find the dependent libraries (derp). Then I noticed the cabal file, so I moved on to using cabal.

I then attempted to run `cabal install` only to be presented with conflicts which could not be resolved (expected). Moved to `cabal install --only-dependencies` -- failed. I tried sandboxes to install each package, but I could not get it to a state where I could build all of the dependencies.

What is the best course of action? Why are the versions so restrictive when it's not easy to install them?

**Comment by Eelis** [comment]
- What version of the Haskell platform are you using?
- What conflicts does "cabal install" give?

**Comment by willkill07** [comment]
What versions of GHC and the Haskell platform are you using?

```
$ brew cask info haskell-platform
haskell-platform: 8.0.2
https://www.haskell.org/platform/
/usr/local/Caskroom/haskell-platform/8.0.2 (311MB)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/haskell-platform.rb
==> Name
Haskell Platform
==> Artifacts
Haskell Platform 8.0.2 Full 64bit-signed.pkg (pkg)
```

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

What conflicts does "cabal install" give?

```
$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: cxxdraft-htmlgen-0 (user goal)
trying: exceptions-0.8.3/installed-74U... (dependency of temporary-1.2.0.4)
next goal: HaTeX (dependency of cxxdraft-htmlgen-0)
rejecting: HaTeX-3.17.1.0/installed-EFA..., HaTeX-3.17.1.0, HaTeX-3.17.0.2,
HaTeX-3.17.0.1, HaTeX-3.17.0.0 (conflict: cxxdraft-htmlgen => HaTeX>=3.16 &&
<3.17)
rejecting: HaTeX-3.16.2.0, HaTeX-3.16.1.1, HaTeX-3.16.1.0, HaTeX-3.16.0.0
(conflict: exceptions => transformers==0.5.2.0/installed-0.5..., HaTeX =>
transformers>=0.2.2 && <0.5)
rejecting: HaTeX-3.15.0.0, HaTeX-3.14.0.0, HaTeX-3.13.1.0, HaTeX-3.13.0.1,
HaTeX-3.13.0.0, HaTeX-3.12.0.0, HaTeX-3.11.0.1, HaTeX-3.11.0.0,
HaTeX-3.10.0.0, HaTeX-3.9.1.0, HaTeX-3.9.0.0, HaTeX-3.8.0.0, HaTeX-3.7.0.0,
HaTeX-3.6.1.0, HaTeX-3.6.0.1, HaTeX-3.6, HaTeX-3.5, HaTeX-3.4, HaTeX-3.3,
HaTeX-3.2.0.1, HaTeX-3.2, HaTeX-3.1.0, HaTeX-3.0.0, HaTeX-2.1.3, HaTeX-2.1.2,
HaTeX-2.1.1, HaTeX-2.1.0, HaTeX-2.0.1, HaTeX-2.0.0, HaTeX-1.0.1, HaTeX-1.0.0
(conflict: cxxdraft-htmlgen => HaTeX>=3.16 && <3.17)
Dependency tree exhaustively searched.
```

**Comment by Eelis** [comment]
Ah, I hadn't tested with 8.0 yet.

The upper bounds on the dependency versions are due to some dubious policy that as far as I can see just causes headaches, so I've committed a patch that removes the upper bounds. For me it now works with 8.0. Can you give it a try?

**Comment by willkill07** [comment]
Good news: it builds properly

Bad news: it complains about `centering` when running the script

```
genhtml.hs:

undefined command: "centering" at: }m{1.2in}|@{}p{0.2\normalbaselineskip}@{}|m{1.8in}
CallStack (from HasCallStack):
  error, called at ./LaTeXParser.hs:333:28 in main:LaTeXParser
```

**Comment by Eelis** [comment]
Ah, I've pushed some commits that should help with that.

(The reason I hadn't noticed the problem is that I generate eel.is/c++draft from my [cxxdraft-htmlgen-fixes](https://github.com/Eelis/draft/commits/cxxdraft-htmlgen-fixes) branch.)

**Comment by willkill07** [comment]
Pulled the changes and everything works as expected with Haskell. Ran into a node problem but I fixed it.

* The `mathjax-node` package v1.0 removed all CLI tools under `bin`
* There is a new package `mathjax-node-cli` (https://github.com/mathjax/mathjax-node-cli/) which has the `tex2html` command
* An absolute path referenced the location of `tex2html` when the user should already have it added to their path, so I changed the absolute path to just the executable name

After I made the change to install `mathjax-node-cli` I encountered an error while writing:
```
Writing to 14882/
  toc
  generalindex
genhtml.hs: user error (Text.Regex.Posix.String died: (ReturnCode 17,"illegal byte sequence"))
```

**Comment by Eelis** [comment]
Thanks for the information about mathjax-node-cli, I've pushed a commit to use it.

I can't reproduce the regex problem, but can you see if changing regex-compat to regex-compat-tdfa in cxxdraft-htmlgen.cabal makes any difference?

**Comment by willkill07** [comment]
Yes, that does make a difference. All works with `regex-compat-tdfa` and the other changes from before
