### ISSUE TITLE
Issues with [facet.num.put.virtuals] p5

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#26]
First, the bullet number for 5.1 and the paragraph number overlap.
Second, the line breaks before "A local variable `punct`..." and "Decimal point characters..." aren't rendered.

**Comment by Eelis** [comment]
Line breaks fixed. Will fix overlapping numbers later.

**Comment by Eelis** [comment]
Note that to get the fix for the overlapping numbers, you need the https://github.com/Eelis/draft/commit/60fb71a63cca9aa499275040c64608725098377c commit as well.

Thanks for the report!
