### ISSUE TITLE
Feature request: syntax highlighting

### ISSUE THREAD

**Issue by dhouck** [Eelis/cxxdraft-htmlgen#29]
I often find it difficult to read the draft code without syntax highlighting. Currently I don’t know of any syntax highlighter which handles all the code examples in the standard correctly (without calling out to a compiler for parsing), but in most cases even mostly-correct highlighting would be an improvement.

I don’t know anything about syntax highlighting libraries in Haskell or Node, or whether you’d be willing to add extra dependencies for this, but I do think it would make things easier to read. If you are willing to add a dependency on Python, I’d recommend going with Pygments; it has some weird behavior around C++ code, but in most cases it handles things well. In some cases involving newer literal features it makes things worse (although [I have an open PR for that](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/723)), but the rest of the time I think it would really improve readability.

**Comment by Eelis** [comment]
Thanks for the suggestion.
