### ISSUE TITLE
eel.is domain name is expired

### ISSUE THREAD

**Issue by eerorika** [Eelis/cxxdraft-htmlgen#33]
I'm terribly sorry for the noise, if this is the wrong place to report this, but it would seem that eel.is domain has expired (or banned or something else; I don't speak German) and responds with a placeholder site.

>  Diese Domain wurde gesperrt...

> Falls Sie der Administrator dieser Domain
> sind und Fragen zur Sperrung Ihrer
> Domain haben, wenden Sie sich bitte
> an unser Support-Team.

**Comment by Eelis** [comment]
Thanks, I've sent the domain guys some moneys. Should hopefully be back up in a day or two.

**Comment by Eelis** [comment]
Fixed.
