### ISSUE TITLE
Links in full.html should be links to itself with anchors only

### ISSUE THREAD

**Issue by dimztimz** [Eelis/cxxdraft-htmlgen#38]
The links in `full.html` link to the smaller documents, e.g. `<a href='bla.bla#anchor.bla.bla'>` instead they should only link with the anchor `<a href='#anchor.bla.bla'`.

**Comment by Eelis** [comment]
Agreed

**Comment by Eelis** [comment]
In fact, more generally (not just in `full`), links should be made local if the target is on the current page. E.g. the "well-formed" link in [intro.defs#defns.ill.formed](http://eel.is/c++draft/intro.defs#defns.ill.formed).

**Comment by dimztimz** [comment]
Just tested again, it is better, but not complete.

The links that link to grammar rules still link to the small pages.
e.g. primary-expression link (in full.html) is http://eel.is/c++draft/expr.prim#nt:primary-expression
