### ISSUE TITLE
time.duration.io 404s

### ISSUE THREAD

**Issue by johelegp** [Eelis/cxxdraft-htmlgen#39]
Greetings.

https://wg21.link/time.duration.io doesn't work, unlike http://eel.is/c++draft/time.duration.io.

Thanks for this useful tool.

**Comment by m-ou-se** [comment]
The link should work now. I updated wg21.link's list of redirects. I'll automate this at some point.

**Comment by johelegp** [comment]
Thank you.

**Comment by johelegp** [comment]
@m-ou-se Please, update them again.
