### ISSUE TITLE
[sf.cmath] slightly broken

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#4]
http://eel.is/c++draft/sf.cmath is slightly broken, e.g., the "overloads!floating point" at the start of p3, the "NaNdomain error" at the start of p4, the stray text at the beginning of each subclause, and the stray "special functions|)" at the end.

**Comment by Eelis** [comment]
Thanks!

This looks like a problem with the LaTeX sources. I've submitted a pull request here: https://github.com/cplusplus/draft/pull/668

**Comment by Eelis** [comment]
Fixed.
