### ISSUE TITLE
\nodiffref should be but isn't generating paragraph numbers

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#40]
http://eel.is/c++draft/diff.cpp17.depr has only a single paragraph number.

**Comment by timsong-cpp** [comment]
It also looks like source links aren't generated for these paragraphs.

**Comment by Eelis** [comment]
Thanks for the report. The paragraph numbers are fixed by fe0d9afd45f5553aca31ddcb1fec0aca0cb5d0e8 and 08a7f3c6166411972974b10ddd225fb7dca9e30e. I've created a [separate issue](https://github.com/Eelis/cxxdraft-htmlgen/issues/42) for the source links.
