### ISSUE TITLE
'\setlength{\emergencystretch}{1em}' renders to '1em'

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#44]
For example, http://eel.is/c++draft/class.base.init#7.note-1, http://eel.is/c++draft/except.throw#7.note-1

**Comment by Eelis** [comment]
Fixed by https://github.com/Eelis/cxxdraft-htmlgen/commit/6eb4572ac9bd2a87b22ffeb6585e79638ca5be2d , thanks for the report.
