### ISSUE TITLE
'\quad' generated in [sf.cmath]

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#45]
e.g., http://eel.is/c++draft/sf.cmath.legendre

**Comment by Eelis** [comment]
Hmm, it seems that unlike MathJax, KaTeX *does* support \quad inside \text, so I should look into using KaTeX instead of MathJax.

**Comment by Eelis** [comment]
Turns out KaTeX has other problematic limitations (such as lack of support for `\mbox` and the `eqnarray*` environment), so I've committed a workaround instead. Thanks for the report.
