### ISSUE TITLE
multicolfloattable environments not rendered correctly

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#46]
e.g., http://eel.is/c++draft/headers#tab:cpp.library.headers

**Comment by Eelis** [comment]
Fixed by 3dc7f4ee8a3c45304a61baf3bc76594ce32d1d71, thanks for the report!

**Comment by Eelis** [comment]
Reopening because the border around the table is broken in Chromium (but not in Firefox for some reason).

**Comment by Eelis** [comment]
Fixed by f1eff83a976b3eb3ff717aa11c3df2515da3e299.
