### ISSUE TITLE
Single page document

### ISSUE THREAD

**Issue by SimonEbner** [Eelis/cxxdraft-htmlgen#47]
Great tool! Any reason why you did not consider a single page document? Would you guide me to some particular direction if I wanted to generate a single page document. Would you recommend a postprocessing or update the code?

**Comment by SimonEbner** [comment]
Did not see the /full until now. Sorry about the noise.

**Comment by BitonicEelis** [comment]
Yeah, I tend not to advertise the single page version because it takes a long time to load, it sometimes crashes browsers, and it puts more strain on the little vps hosting it.
