### ISSUE TITLE
[optional] tables are broken

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#5]
See, e.g., http://eel.is/c++draft/optional.object.assign.

**Comment by Eelis** [comment]
Hmm, I suspect that this might automatically get fixed when this upstream FIXME is resolved: https://github.com/cplusplus/draft/blob/master/source/tables.tex#L695

**Comment by Eelis** [comment]
Fixed by 6b599690bd1bda9153a2cbcfd2ce34d591b48183.
