### ISSUE TITLE
Feature request / discussion: Adding a "search" feature to the generated website

### ISSUE THREAD

**Issue by maddouri** [Eelis/cxxdraft-htmlgen#54]
Hello,

Would it be possible to add a "search" feature to the generated website, please?

### Motivation

IMHO, integrating such a feature into the website would make finding content easier for users.

### Examples of websites implementing a similar feature

1. [CppReference](https://en.cppreference.com/)
    1. This wiki allows the user to search for content using the search box that is located at the top-right corner.
    1. The result page shows the list of matches, if any.
    1. The result page also also adds links to online search engines _(currently Google, Bing and DuckDuckGo)_. The URLs of those links already contain the query terms as well as search-engine-specific "operators" for launching the search only on the `en.cppreference.com` domain (e.g. `site:en.cppreference.com` for Google). This is quite handy when the wiki search engine is unable to find the content that the user is looking for.
1. [OpenCV Docs (_"newer"_ website)](https://docs.opencv.org/4.0.0/index.html)
    1. This doxygen-generated documentation website shows 2 search boxes.
    1. The first search box is located at the top of the page and invokes Google search on `docs.opencv.org`.<br>Actually, the result page contains multiple "tabs". Each tab corresponds to a particular major version of the library (e.g. 2.4.x, 3.x, etc.), plus an "All" tab containing results from the other tabs.<br>The result "page" is shown in a `<div>` that is displayed on top of the current page.
    1. The second search box is located below the first one, on the right.<br>If my understanding is correct, it uses a doxygen-generated search engine.<br>The results appear in a popup under the search box.

### Current workarounds

Depending on my particular query, I use one or a combination of:

1. `Ctrl+F` in the "index" pages (such as http://eel.is/c++draft/generalindex and http://eel.is/c++draft/libraryindex)
1. `Ctrl+F` in a standard draft's PDF file (e.g. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf)
1. Type my query in Google, followed by `site:eel.is` ([example](https://www.google.com/search?q=anonymous+union+site%3Aeel.is))
1. Configure a custom search engine in my browser based on `3` (This is is obviously handy when I'm using my own system.. which is not always the case ;)
1. Use [CppReference](https://en.cppreference.com/)

### Final thoughts

1. I think that a simpler version of the Google-based search of OpenCV's documentation might be a good fit for http://eel.is/c++draft. This might be easier to setup than developing a custom one (or even using something like a javascript library that may not provide high-quality results)
1. The search box should probably be displayed on all pages. This avoids minor inconveniences such as needing to go back to the home page in order to launch a new search.
1. It may or may not be useful to provide an option/checkbox to display the result page either in the current browser window/tab, or in a new one.

**Comment by Eelis** [comment]
The index and existing search engines are good enough for me.
