### ISSUE TITLE
[Potentially upstream issue] Index error for basic.def.odr 

### ISSUE THREAD

**Issue by whisperity** [Eelis/cxxdraft-htmlgen#58]
*One Definition Rule* is linked to [`[basic.def]`](http://eel.is/c++draft/basic.def#:one-definition_rule) to a seemingly empty arrow at the bottom, instead of [`[basic.def.odr]`](http://eel.is/c++draft/basic.def.odr).

**Comment by Eelis** [comment]
Fixed, thanks for the report.
