### ISSUE TITLE
Nested notes/examples interacts poorly with collapsing alternate CSS

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#60]
Trying to expand the inner note/example will instead hide everything. For example, the example in the note at http://eel.is/c++draft/class.conv.ctor#2.note-1

**Comment by Eelis** [comment]
I don't want to use Javascript for this thingy, and as far as I can tell, the only way to do it with CSS is with `:has()`, which [apparently](https://caniuse.com/#feat=css-has) no browser currently supports.

So I hope you're patient, because this may take a decade to fix. :)

**Comment by timsong-cpp** [comment]
Not even `:has()`, since it apparently [can't be used in stylesheets](https://developer.mozilla.org/en-US/docs/Web/CSS/:has). This might take a few decades 😂

**Comment by Eelis** [comment]
Wow, I didn't realize they introduced those [Selector Profiles](https://drafts.csswg.org/selectors/#profiles) *specifically* to make `:has()` not work by default. What a mess...

**Comment by timsong-cpp** [comment]
The perhaps more practical fix - if we want to fix this at all - is to have only one level of collapsing (e.g., uncollapsing a note also shows any nested examples).

**Comment by Eelis** [comment]
One level of collapsing wouldn't solve the problem I think, because the problem already occurs when a sentence inside a (non-nested) uncollapsed note is selected.

**Comment by Eelis** [comment]
Closing because the stylesheet was removed.
