### ISSUE TITLE
\tref is rendered incorrectly

### ISSUE THREAD

**Issue by cpplearner** [Eelis/cxxdraft-htmlgen#61]
See e.g. http://eel.is/c++draft/lex.key, where `\tref{keywords}` is rendered as `[tab:keywords]Table *tab:keywords`.

Might be related to https://github.com/cplusplus/draft/commit/569f41ce7410becceaf5537c148b1bc420139bb0.

**Comment by Eelis** [comment]
Thanks for the report.

https://github.com/cplusplus/draft/issues/2674 also looks relevant.

**Comment by Eelis** [comment]
Fixed by 0cb648f15f3125c192688014486ce0c54816f33d.
