### ISSUE TITLE
Problems generating the newest HTML standard revision (n4830)

### ISSUE THREAD

**Issue by TomasLesicko** [Eelis/cxxdraft-htmlgen#63]
Hi,

I'm having trouble generating the newest standard revision (master branch / tag n4830 of https://github.com/cplusplus/draft). Judging from http://eel.is/c++draft/, it should be possible to generate it. I can still generate n4820, but generating n4830 throws the following error:

```
Loading chapters
  intro... 38 sections
  ...
  numerics... 152 sections
  time... cxxdraft-htmlgen: 

undefined command: "fmtgrammarterm" at: {chrono-format-spec}
according to the following sy
CallStack (from HasCallStack):
  error, called at LaTeXParser.hs:344:28 in main:LaTeXParser

```

**Comment by Eelis** [comment]
Unfortunately, cxxdraft-htmlgen no longer works with the unmodified draft sources. I've now pushed https://github.com/Eelis/cxxdraft-htmlgen/commit/b53077a5682c1f6bfc32d9242987eb8712c56924 to clarify that.

Thanks for the report.
