### ISSUE TITLE
Feature request: generate arbitrary chunks

### ISSUE THREAD

**Issue by hatcat** [Eelis/cxxdraft-htmlgen#72]
I would like to be able to generate a small 5 page chunk of the standard, pinned to N4861, for example from [stmt.stmt] through to [stmt.for] inclusive, perhaps with a syntax like http://eel.is/c++draft/stmt.stmt:stmt.for

Unfortunately, I have no Haskell. Would you be able to implement this feature?

**Comment by Eelis** [comment]
This would probably be doable if the pages were generated dynamically. However:
- the pages are generated statically
- I don't want to switch to dynamic generation
- I can't think of a reasonable (i.e. non-O(n^2)) way to generate all chunks statically.

**Comment by hatcat** [comment]
Thanks Eelis. Particularly, there are 365 chunks I want generated. Would this simplify things? If, for example, I provided 365 stable-index ranges, would that work? if it's too much effort, I quite understand: maybe I'll fork, learn me some Haskell and see what happens.

**Comment by Eelis** [comment]
Yeah, I would only be interested in implementing this myself if I could make it a general facility that works for arbitrary ranges. So for a more specialized application, I think you'd better fork, yes.
