### ISSUE TITLE
Footnote in [string.view.template] not correctly rendered

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#8]
The `basic_string_view` synopsis in [string.view.template] contains a footnote after `typedef const_iterator iterator;`, which is not correctly rendered in the [HTML version](http://eel.is/c++draft/string.view.template).

A similar issue affects the `explicit operator basic_string()` in [[string.view.ops]](http://eel.is/c++draft/string.view.ops).

**Comment by Eelis** [comment]
Fixed, thanks!
