### ISSUE TITLE
Dark color scheme

### ISSUE THREAD

**Issue by Kojoley** [Eelis/cxxdraft-htmlgen#82]
It would be nice to have a dark color scheme.

There is a semi-standard way to respect user OS settings https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme.

**Comment by Eelis** [comment]
Sounds good!
I'll take a look when I get Firefox 87 (which will feature some new developer tool buttons for testing light/dark themes).

**Comment by Kojoley** [comment]
Much appreciated!
