### ISSUE TITLE
Missing paragraph breaks for itemdescr inside list item 

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#86]
https://eel.is/c++draft/range.nonprop.cache#1.6

**Comment by JohelEGP** [comment]
See https://github.com/Eelis/draft/blob/e133ce059e98c356f29c1406f4cbcd66a56e12f5/source/ranges.tex#L3207-L3208. Is the problem present in the PDF too?

**Comment by Eelis** [comment]
Fixed by https://github.com/Eelis/draft/commit/ba36a67f2c7ec8f9e773b1c13104bdaa5153bd43, thanks for the report!
