### ISSUE TITLE
Consider replacing "Working Draft" with something more appropiate

### ISSUE THREAD

**Issue by JohelEGP** [Eelis/cxxdraft-htmlgen#87]
See https://github.com/cplusplus/draft/issues/4726. In summary, these are not really Working Drafts, which are published as N-papers to WG21's mailing lists.
![1625234236](https://user-images.githubusercontent.com/21071787/124285548-01c22500-db1c-11eb-84f8-7b2b91c49fe3.png)

**Comment by Eelis** [comment]
What is the title used in PDFs generated by the draft sources?

**Comment by JohelEGP** [comment]
Same as above.
![1625234534](https://user-images.githubusercontent.com/21071787/124286117-9cbaff00-db1c-11eb-8331-005d74da1ad8.png)

**Comment by Eelis** [comment]
Thanks. Then I'm content with matching the PDFs.

**Comment by Eelis** [comment]
One thing I *could* do is make a toc page header similar to the one in your screenshot, linking to the commit that the html was generated from, to make it clear that it doesn't correspond to an actual published paper. That could be nice.

**Comment by Eelis** [comment]
I'll use this issue to track that change.

**Comment by JohelEGP** [comment]
I took that from https://eel.is/c++draft/. "LaTeX sources" already does that, currently linking to http://github.com/Eelis/draft/commit/192138ebe9f8c866ad4bf311d2f1a2162a139989.

**Comment by Eelis** [comment]
Yeah, but if I formatted that link in a header like:

     Document Number: n/a, commit: 641afd15b0.
     
 then it would be more explicit that the html version does not correspond to a particular published document.

**Comment by Eelis** [comment]
I changed my mind, I'm content with the status quo.
