### ISSUE TITLE
Entities have an invisible &shy; character after an underscore 

### ISSUE THREAD

**Issue by marehr** [Eelis/cxxdraft-htmlgen#88]
Hi!

When copying and pasting code snippets from the standard into an editor you will get compiler errors, because it always copies a [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) unicode character.

For example `to_address` contains that hidden character `to_[hidden whitespace]address`.

It would be nice, if the html wouldn't contain those hidden whitespaces in entities.

See ![Screenshot from 2021-09-15 12-33-03](https://user-images.githubusercontent.com/103778/133418994-e283678f-9806-414f-8f54-0029a4492414.png) and 
![grafik](https://user-images.githubusercontent.com/103778/133419051-e215235a-7715-4d41-86cf-05f1891a9758.png).

**Comment by Eelis** [comment]
The soft hyphens are necessary to achieve good layout.

**Comment by JohelEGP** [comment]
> When copying and pasting

The same happened to me, but it stopped somewhen along the way.

**Comment by AaronBallman** [comment]
I just ran into this as well: https://reviews.llvm.org/D146187#4201921

**Comment by Eelis** [comment]
Thanks for the reports. I realized I can use CSS to work around this problem, so I've pushed a commit to do so. Should be mostly fixed now.
