### ISSUE TITLE
fatal: No remote configured to list refs from.

### ISSUE THREAD

**Issue by JohelEGP** [Eelis/cxxdraft-htmlgen#89]
```
[johel@sundown cxxdraft-htmlgen]$ stack exec cxxdraft-htmlgen /home/johel/Documents/C++/Repos/waarudo-builds/pdf/documentations WithExtension
fatal: No remote configured to list refs from.
cxxdraft-htmlgen: readCreateProcess: git "ls-remote" "--get-url" (exit 128): failed
```
```
ghc-8.10.5-1
stack-2.7.1-1
```
I haven't built in a long time and this is what I get.

**Comment by Eelis** [comment]
Is it possible that `/home/johel/Documents/C++/Repos/waarudo-builds/pdf/documentations` is not the draft checkout directory itself, but a directory containing the draft checkout directory? If so, try passing `/home/johel/Documents/C++/Repos/waarudo-builds/pdf/documentations/draft` instead, where `draft` is the name of the directory containing the checkout (which defaults to `draft` but can be something else).

**Comment by JohelEGP** [comment]
Thank you.

So it turns out that you really need a checkout of the draft. This time, I had copied the directory structure instead.
