### ISSUE TITLE
\iref{term.unevaluated.operand} is handled as a reference to [term.unevaluated.operand] section which doesn't exist

### ISSUE THREAD

**Issue by languagelawyer** [Eelis/cxxdraft-htmlgen#91]
`term.unevaluated.operand` was introduced in https://github.com/cplusplus/draft/pull/4941 as a `\label`

**Comment by languagelawyer** [comment]
There is also `term.odr.use`

**Comment by JohelEGP** [comment]
And more are on the way: https://github.com/cplusplus/draft/pull/5104.

**Comment by Eelis** [comment]
Should be fixed. Thanks for the report!
