### ISSUE TITLE
Consider enforcing HTTPS through URL rewriting

### ISSUE THREAD

**Issue by StephanTLavavej** [Eelis/cxxdraft-htmlgen#93]
Many thanks for maintaining https://eel.is/c++draft/ :heart_eyes_cat: (and apologies for submitting this as a GitHub issue, I didn't see any contact info for the website).

Feature request: I observe that `eel.is` supports HTTPS but doesn't enforce it through URL rewriting. Configuring nginx to rewrite http://eel.is/c++draft/ to https://eel.is/c++draft/ would make it easier for users to share HTTPS links (instead of manually adjusting links).

**Comment by Eelis** [comment]
I don't understand the problem. You can link to http if you want, or you can link to https if you want. So you have optimal flexibility. What's all this nonsense talk about "enforcing" stuff?
