### ISSUE TITLE
[format.string.escaped] example is rendered incorrectly 

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#98]
https://eel.is/c++draft/format.string.escaped#example-1, in particular the `s3` line.

**Comment by Eelis** [comment]
Thanks for the report!

By the way, I'm confused about that `s3` line:
```
string s3 = format("[{:?}] [{:?}]", '\'', '"');         // s3 has value: ['\”, '"']
```
Shouldn't there be two pairs of `[]` in the result, given that there are two pairs of `[]` in the format string?

**Comment by timsong-cpp** [comment]
Yeah that sounds like a bug in the paper.

**Comment by JohelEGP** [comment]
Others bugs were revealed by an implementor in https://github.com/cplusplus/draft/pull/5751, but not that one.

**Comment by Eelis** [comment]
Ah ok, thanks for the link.

**Comment by tkoeppe** [comment]
@Eelis: tangentially, would you consider setting up a harmonizing family of fonts for your HTML rendition? There are lots of options, but anything where the roman, italics, and monotype have the same contrast and metrics would perhaps make the HTML view even nicer? (I can make some suggestions if you like.)

**Comment by Eelis** [comment]
@tkoeppe I see that I currently use Times New Roman for most things, Courier New for code, and Arial for sans-serif. Looks alright to me, and I like using super standard fonts. But if you have ideas about alternative choices that could look significantly better, I'm intrigued. :)

**Comment by Eelis** [comment]
Reopening because now there's still a bad quotation mark in there.

**Comment by tkoeppe** [comment]
Right, those fonts are pretty poorly matched. Courier New is among the worst, having complely different sizes and contrast (it's too large and too thin). To see what I mean, just compare this against a harmonizing family. For example, DejaVu Serif, DejaVu Sans, and DejaVu Sans Mono. There are many more nowadays (e.g. Noto {Serif, Sans, Mono, Emoji}).

**Comment by Eelis** [comment]
Tried DejaVu and Noto just now, but neither seemed like an improvement over the status quo.

**Comment by tkoeppe** [comment]
Have you set all the fonts jointly (e.g. body font to DejaVu Serif, code font to DejaVu Sans Mono)? OK, if you don't find it an improvement that's fair enough.

**Comment by Eelis** [comment]
One difference between the draft pdf and the pages generated by cxxdraft-htmlgen, is that the pdf only has to deal with a fixed page size, and a page size that's quite big. In contrast, cxxdraft-htmlgen tries to make an effort to still look decent at smaller page sizes. That's a challenge though, because the narrower the page, the more often layout problems occur, e.g. section headers overflowing, code blocks overflowing, grammar rules overflowing, table cells overflowing, and so on. Changing to a much wider font (such as DejaVu or DejaVu Condensed), and increasing the size of code increases the frequency with which such problems occur, harming readability.

**Comment by tkoeppe** [comment]
Oh, it's specifically with width of DejaVu you mind? That's fair enough. It was just an example to show harmonizing contrast and metrics. But you can do the same with an overall narrower font family of course.

**Comment by Eelis** [comment]
Noto 11pt is wider than Times New Roman 11pt, causing the kind of overflows I mentioned. Noto 10pt makes the text smaller and harder to read.

![image](https://user-images.githubusercontent.com/22357/186020263-be6a3bfe-742a-4e96-a2c5-8ed84b2b6cac.png)

**Comment by tkoeppe** [comment]
Yeah. We might need an actual narrower font.

**Comment by Eelis** [comment]
Sounds good. I'll look into it when I get around to it, thanks! (Or feel free to submit a PR.)
